server {
    listen 80;
    server_name api.uplifts.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.uplifts.dev;

    root /var/www/mentorship/mentorship-backend/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/api.uplifts.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.uplifts.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}
