<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Job;
use Carbon\Carbon;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Full Stack Developer',
                'company' => 'Tech Innovations Sdn Bhd',
                'description' => 'We are looking for an experienced Full Stack Developer to join our growing team. You will work on developing web applications using React, Node.js, and MongoDB.',
                'requirements' => ['React', 'Node.js', 'JavaScript', 'MongoDB', 'REST API', 'Git'],
                'location' => 'Kuala Lumpur, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (2-5 years)',
                'salary' => 'RM 6,000 - RM 10,000',
                'source' => 'JobStreet',
                'external_url' => 'https://jobstreet.com.my/job/12345',
                'posted_date' => Carbon::now()->subDays(2),
                'is_active' => true,
            ],
            [
                'title' => 'Frontend Developer (React)',
                'company' => 'Digital Solutions Malaysia',
                'description' => 'Join our frontend team to build modern, responsive web applications. Must have strong React skills and eye for design.',
                'requirements' => ['React', 'JavaScript', 'HTML', 'CSS', 'TypeScript', 'Tailwind CSS'],
                'location' => 'Petaling Jaya, Selangor',
                'job_type' => 'Full-time',
                'experience_level' => 'Junior (1-2 years)',
                'salary' => 'RM 4,000 - RM 6,500',
                'source' => 'LinkedIn',
                'external_url' => 'https://linkedin.com/jobs/12345',
                'posted_date' => Carbon::now()->subDays(5),
                'is_active' => true,
            ],
            [
                'title' => 'Backend Developer (Node.js)',
                'company' => 'StartupHub KL',
                'description' => 'Seeking a backend developer to build scalable APIs and microservices. Experience with Node.js, Express, and MongoDB required.',
                'requirements' => ['Node.js', 'Express', 'MongoDB', 'REST API', 'Docker', 'AWS'],
                'location' => 'Kuala Lumpur, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (3-5 years)',
                'salary' => 'RM 7,000 - RM 11,000',
                'source' => 'Hiredly',
                'external_url' => 'https://hiredly.com/jobs/12345',
                'posted_date' => Carbon::now()->subDays(1),
                'is_active' => true,
            ],
            [
                'title' => 'Data Scientist',
                'company' => 'Analytics Corp Malaysia',
                'description' => 'We need a Data Scientist to analyze large datasets and build machine learning models. Python and TensorFlow experience required.',
                'requirements' => ['Python', 'Machine Learning', 'TensorFlow', 'Pandas', 'SQL', 'Data Visualization'],
                'location' => 'Cyberjaya, Selangor',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (3-5 years)',
                'salary' => 'RM 8,000 - RM 13,000',
                'source' => 'JobStreet',
                'external_url' => 'https://jobstreet.com.my/job/23456',
                'posted_date' => Carbon::now()->subDays(3),
                'is_active' => true,
            ],
            [
                'title' => 'Junior Python Developer',
                'company' => 'Code Academy Sdn Bhd',
                'description' => 'Great opportunity for fresh graduates! Learn while you work on real projects. Python, Django, and web development.',
                'requirements' => ['Python', 'Django', 'HTML', 'CSS', 'JavaScript', 'SQL'],
                'location' => 'Shah Alam, Selangor',
                'job_type' => 'Full-time',
                'experience_level' => 'Entry-level (0-1 years)',
                'salary' => 'RM 3,000 - RM 4,500',
                'source' => 'LinkedIn',
                'external_url' => 'https://linkedin.com/jobs/23456',
                'posted_date' => Carbon::now()->subDays(7),
                'is_active' => true,
            ],
            [
                'title' => 'Mobile App Developer (React Native)',
                'company' => 'AppMakers Studio',
                'description' => 'Build cross-platform mobile applications using React Native. Work on exciting projects for Malaysian startups.',
                'requirements' => ['React Native', 'JavaScript', 'iOS', 'Android', 'Firebase', 'Redux'],
                'location' => 'Kuala Lumpur, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (2-4 years)',
                'salary' => 'RM 6,500 - RM 9,500',
                'source' => 'Hiredly',
                'external_url' => 'https://hiredly.com/jobs/23456',
                'posted_date' => Carbon::now()->subDays(4),
                'is_active' => true,
            ],
            [
                'title' => 'DevOps Engineer',
                'company' => 'CloudTech Malaysia',
                'description' => 'Manage CI/CD pipelines, Docker containers, and Kubernetes clusters. AWS experience is a plus.',
                'requirements' => ['Docker', 'Kubernetes', 'Jenkins', 'AWS', 'Linux', 'Terraform'],
                'location' => 'Cyberjaya, Selangor',
                'job_type' => 'Full-time',
                'experience_level' => 'Senior (5+ years)',
                'salary' => 'RM 10,000 - RM 15,000',
                'source' => 'JobStreet',
                'external_url' => 'https://jobstreet.com.my/job/34567',
                'posted_date' => Carbon::now()->subDays(6),
                'is_active' => true,
            ],
            [
                'title' => 'UI/UX Designer',
                'company' => 'Creative Agency KL',
                'description' => 'Design beautiful and functional user interfaces. Figma expertise required. Work with top Malaysian brands.',
                'requirements' => ['Figma', 'Adobe XD', 'UI Design', 'UX Research', 'Prototyping', 'Wireframing'],
                'location' => 'Kuala Lumpur, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (3-5 years)',
                'salary' => 'RM 5,500 - RM 8,500',
                'source' => 'LinkedIn',
                'external_url' => 'https://linkedin.com/jobs/34567',
                'posted_date' => Carbon::now()->subDays(2),
                'is_active' => true,
            ],
            [
                'title' => 'PHP Laravel Developer',
                'company' => 'WebDev Solutions',
                'description' => 'Develop enterprise web applications using Laravel framework. MySQL and REST API experience required.',
                'requirements' => ['PHP', 'Laravel', 'MySQL', 'JavaScript', 'Vue.js', 'REST API'],
                'location' => 'Penang, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (2-4 years)',
                'salary' => 'RM 5,000 - RM 8,000',
                'source' => 'Hiredly',
                'external_url' => 'https://hiredly.com/jobs/34567',
                'posted_date' => Carbon::now()->subDays(8),
                'is_active' => true,
            ],
            [
                'title' => 'Machine Learning Engineer',
                'company' => 'AI Innovations Sdn Bhd',
                'description' => 'Build and deploy ML models for production. Experience with TensorFlow, PyTorch, and cloud platforms.',
                'requirements' => ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'Deep Learning', 'AWS'],
                'location' => 'Kuala Lumpur, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Senior (5+ years)',
                'salary' => 'RM 12,000 - RM 18,000',
                'source' => 'JobStreet',
                'external_url' => 'https://jobstreet.com.my/job/45678',
                'posted_date' => Carbon::now()->subDays(1),
                'is_active' => true,
            ],
            [
                'title' => 'WordPress Developer',
                'company' => 'Digital Marketing Hub',
                'description' => 'Create custom WordPress themes and plugins. PHP and JavaScript knowledge required.',
                'requirements' => ['WordPress', 'PHP', 'JavaScript', 'HTML', 'CSS', 'MySQL'],
                'location' => 'Johor Bahru, Johor',
                'job_type' => 'Full-time',
                'experience_level' => 'Junior (1-3 years)',
                'salary' => 'RM 3,500 - RM 5,500',
                'source' => 'LinkedIn',
                'external_url' => 'https://linkedin.com/jobs/45678',
                'posted_date' => Carbon::now()->subDays(9),
                'is_active' => true,
            ],
            [
                'title' => 'Quality Assurance Engineer',
                'company' => 'Software Testing Lab',
                'description' => 'Test web and mobile applications. Automation testing experience with Selenium preferred.',
                'requirements' => ['Manual Testing', 'Selenium', 'Test Automation', 'JavaScript', 'API Testing'],
                'location' => 'Kuala Lumpur, Malaysia',
                'job_type' => 'Full-time',
                'experience_level' => 'Mid-level (2-4 years)',
                'salary' => 'RM 4,500 - RM 7,000',
                'source' => 'Hiredly',
                'external_url' => 'https://hiredly.com/jobs/45678',
                'posted_date' => Carbon::now()->subDays(5),
                'is_active' => true,
            ],
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        }
    }
}
